apiVersion: v1
kind: ConfigMap
metadata:
  name: sirato-nginx-conf
data:
  nginx.conf: |
    user nginx;
    error_log  /var/log/nginx/error.log;
    events {
    }
    http {
      access_log	/var/log/nginx/access.log;
      server {
          listen       80;
          server_name  _;
          location /api/ {
            proxy_pass http://sirato-api:8090/;
          }
          location / {
            proxy_pass http://sirato-web:3000/;
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sirato-proxy
  name: sirato-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sirato-proxy
  template:
    metadata:
      labels:
        run: sirato-proxy
    spec:
      containers:
      - name: sirato-proxy
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: sirato-nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: sirato-nginx-conf
        configMap:
          name: sirato-nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sirato-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: sirato-proxy
